global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask'
    static_configs:
      - targets: ['flask-app:5000']

rule_files:
  - /etc/prometheus/alerts.yml  # Path to the alert rules file

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']  # Ensure the target is correct

